version: '3.0'
services:
  web:
    image: nginx
    container_name: web
    restart: always
    volumes:
    - ./src:/var/www/html
    - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./configs/nginx/conf.d:/etc/nginx/conf.d
    ports:
    - "8080:80"
    depends_on:
    - php
    - db
  php:
    image: php:7.0-fpm
    container_name: php
    restart: always
    ports:
    - "9000:9000"
    volumes:
    - ./src:/var/www/html
  db:
    image: mysql
    container_name: db
    restart: always
    env_file:
      - ./configs/.ENV
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8580:80"
    links:
      - db